import time

import sys
import time
st = 0.07 # How fast you want the time in between letters to be (stands for "sleep time"
def sp(str):
    for letter in str: 
        sys.stdout.write(letter)
        sys.stdout.flush()
        time.sleep(st)



# Main Code Begins

row_0=['   ', '   ','   ','   ','   ']
row_1=['   ', '   ','   ','   ','   ']
row_2=['   ', '   ','   ','   ','   ']
row_3=['   ', '   ','   ','   ','   ']
row_4=['   ', '   ','   ','   ','   ']


the_maze=[row_0,row_1,row_2,row_3,row_4]


def print_row(i):
    print(the_maze[i][0]+the_maze[i][1]+the_maze[i][2]+the_maze[i][3]+the_maze[i][4])

def open_map():
    print_row(0)
    print_row(1)
    print_row(2)
    print_row(3)
    print_row(4)

current_position=[0,2]
visited_positions=[]

def update_visited_positions():
    if current_position not in visited_positions:
        visited_positions.append(current_position.copy())

def update_maze():
    for i in visited_positions:
        first_coordinate=i[0]
        second_coordinate=i[1]
        the_maze[first_coordinate][second_coordinate]=' O '
    the_maze[current_position[0]][current_position[1]]=' X '

def move_N():
    current_position[0]-=1

def move_S():
    current_position[0]+=1

def move_E():
    current_position[1]+=1

def move_W():
    current_position[1]-=1







def ending():
    sp('It\'s pitch black.')
    time.sleep(2)
    print()
    print()
    sp('You feel the cool ocean breeze on your face and bare feet. You open your eyes and take it all in.')
    time.sleep(2)
    print()
    print()
    sp('A tropical paradise. The 4 S\'s: Sun, sea, sand... and success!!!')
    time.sleep(2)
    print()
    print()
    sp('Your phone vibrates in the pocket of your shorts. You reach into the pocket and pull out your phone.')
    time.sleep(2)
    print()
    print()
    sp('A text from your boss reads: “Thank you again for all the work you did on your Code Nation gaming project. We\'re excited to have you on board the management team. Enjoy your well deserved break!”')
    time.sleep(2)
    print()
    print()
    sp(f'You worked so hard to get here {name}, you deserve all of this.')
    time.sleep(2)
    print()
    print()
    sp('You reach across and clink your glass, celebrating your promotion. Your significant other throws a smile your way and and congratulates you.')
    time.sleep(2)
    print()
    print()
    sp('“I always believed in you.”')
    time.sleep(2)
    print()
    print()
    print()
    sp("Game over!!!")
    print()
    print()
    exit()



def square_13():
    sp('The screaming of your name stops.')
    time.sleep(2)
    print()
    print()
    sp('The panic and the dread stops.')
    time.sleep(2)
    print()
    print()
    sp('Your heart stops.')
    time.sleep(2)
    print()
    print()
    sp('YOU DIED. :D')
    time.sleep(2)
    print()
    print()
    print()
    sp("Restart game, if you please.")
    print()
    print()
    exit()   



def square_23():
    sp('You stand in the clearing. Tired, afraid and cold.')
    time.sleep(2)
    print()
    print()
    sp('To your South, there\'s more light fog that appears to be covering a passageway in the hedge.')
    time.sleep(2)
    print()
    print()
    sp('Once again, you reach out your arms in front of you as you traverse the fog...')
    time.sleep(2)
    print()
    print()
    ending()



def square_22():
    sp('“You there!” you hear from the Southwest corner.')
    time.sleep(2)
    print()
    print()
    sp("You turn to see a crow perched on the sole branch of a small, dying tree.")
    time.sleep(2)
    print()
    print()
    sp("A talking crow?")
    time.sleep(2)
    print()
    print()
    sp("Is this the voice you heard?")
    time.sleep(2)
    print()
    print()
    sp("'My name is Sirius. Congrats on getting through the maze.'")
    time.sleep(2)
    print()
    print()
    sp("Directly to your East now, you see a clearing littered with flowers of all colours.") 
    time.sleep(2)
    print()
    print()
    sp("Blue, red, yellow, and even some colours you have never seen before.") 
    time.sleep(2)
    print()
    print()
    sp("You'd think your eyes were playing tricks if you hadn't already seen what you've seen by getting this far.") 
    time.sleep(2)
    print()
    print()
    sp("North is back where you came from.") 
    time.sleep(2)
    print()
    print()
    response=input('Which way would you like to go? [North/East/(Open Map)]: ')
    time.sleep(2)
    print()
    print()
    while response != 'North' and response!='East':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [North/East/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            print("I know it's nice and calm here but you really need to keep moving..")
            time.sleep(2)
            print()
            print()
            print("You don't want to be trapped here forever, do you?")
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [North/East/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
    if response == 'North':
            print('You head back North where you came from.')
            time.sleep(2)
            print()
            print()
            move_N()
    elif response == 'East':
        sp("You walk into the clearing, leaving Sirius behind. Carefully treading as not to squash the beautiful flowers.")
        time.sleep(2)
        print()
        print()
        move_E()



def square_25():
    sp('The screaming of your name stops.')
    time.sleep(2)
    print()
    print()
    sp('The panic and the dread stops.')
    time.sleep(2)
    print()
    print()
    sp('Your heart stops.')
    time.sleep(2)
    print()
    print()
    sp('YOU DIED. :D')
    time.sleep(2)
    print()
    print()
    print()
    sp("Restart game, if you please.")
    print()
    print()
    exit()



def square_24():
    sp('Only one torch illuminates your surroundings.')
    time.sleep(2)
    print()
    print()
    sp('The mystery voice is now screaming your name.')
    time.sleep(2)
    print()
    print()
    sp(f'{name}!!!')
    time.sleep(2)
    print()
    print()
    sp(f'{name}!!!')
    time.sleep(2)
    print()
    print()
    sp(f'{name}!!!')
    time.sleep(2)
    print()
    print()
    sp('It\'s coming from the East.')
    time.sleep(2)
    print()
    print()
    sp('As you look in that direction, you see nothing.')
    time.sleep(2)
    print()
    print()
    sp('Only darkness.')
    time.sleep(2)
    print()
    print()
    sp('The voice continues to howl...')
    time.sleep(2)
    print()
    print()
    sp(f'{name}!!!')
    time.sleep(2)
    print()
    print()
    sp(f'{name}!!!')
    time.sleep(2)
    print()
    print()
    sp('There\'s a little wooden sign pitched into the ground on the edge of the darkness.')
    time.sleep(2)
    print()
    print()
    sp('It\'s not well lit here but you can just about make out the message painted on it.')
    time.sleep(2)
    print()
    print()
    sp('“Turn back or face certain death”')
    time.sleep(2)
    print()
    print()
    sp('North is back where you came from.')
    time.sleep(2)
    print()
    print()
    response=input('Which way would you like to go? [East/North/(Open Map)]: ')
    time.sleep(2)
    print()
    print()
    while response != 'East' and response != 'North':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [East/North/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('Those screams will burst your eardrums if you stand here any longer. You should probably move East or North.')
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [East/North/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
    if response == 'East':
        sp('You are drawn to your name.')
        time.sleep(2)
        print()
        print()
        sp('Almost as if a force is gravitating you towards it.')
        time.sleep(2)
        print()
        print()
        sp('Ignoring the sign\'s warning, you enter the darkness.')
        time.sleep(2)
        print()
        print()
        move_E()
    elif response == 'North':
        sp('You turn back to where you came from and hear your name called again from behind you.')
        time.sleep(2)
        print()
        print()
        move_N()



def square_19():
    sp('There isn\'t much around, still just the singular torch lighting the South.')
    time.sleep(2)
    print()
    print()
    sp(f'{name}...')
    time.sleep(2)
    print()
    print()
    sp('It\'s much louder this time.')
    time.sleep(2)
    print()
    print()
    sp('You must be getting close.')
    time.sleep(2)
    print()
    print()
    sp('Up North is back where you came from, towards the golden light.')
    time.sleep(2)
    print()
    print()
    response=input('Which way would you like to go? [South/North/(Open Map)]: ')
    time.sleep(2)
    print()
    print()
    while response != 'South' and response != 'North':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [South/North/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('I\'m starting to think you don\'t want to escape. Buck your ideas up!')
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [South/North/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
    if response == 'South':
        sp('You head towards the torch, following the sound of your name...')
        time.sleep(2)
        print()
        print()
        sp(f'{name}...')
        time.sleep(2)
        print()
        print()
        sp('A spider crawls up from out of your boot and attacks your leg, adding yet another wound to the growing list.')
        time.sleep(2)
        print()
        print()
        sp('It meets a quick end as you stamp it out on your way forward.')
        time.sleep(2)
        print()
        print()
        move_S()
    elif response == 'North':
        sp('The golden light attracts you Northwards.')
        time.sleep(2)
        print()
        print()
        sp('As you carefully tread your way back, you hear your name called again from the South...')
        time.sleep(2)
        print()
        print()
        sp(f'{name}...')
        time.sleep(2)
        print()
        print()
        move_N()



def square_14():
    sp('There appears to be a crack in the hedge to your West and from it, a beaming golden light.')
    time.sleep(2)
    print()
    print()
    sp('You\'re about to peer into the crack, hoping the light won\'t blind you, when you hear it again...')
    time.sleep(2)
    print()
    print()
    sp(f'{name}...')
    time.sleep(2)
    print()
    print()
    sp('The mystery voice.')
    time.sleep(2)
    print()
    print()
    sp('It came from the South.')
    time.sleep(2)
    print()
    print()
    sp('You look in that direction but don\'t see much. Just a singular torch in the distance.')
    time.sleep(2)
    print()
    print()
    sp('To your East is the narrow path.')
    time.sleep(2)
    print()
    print()
    response=input('Which way would you like to go? [West/South/East/(Open Map)]: ')
    time.sleep(2)
    print()
    print()
    while response != 'West' and response != 'South' and response != 'East':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [West/South/East/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('Do you even want to get out of here? You should decide on a direction and head that way.')
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [West/South/East/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
    if response == 'West':
        sp('You can\'t help but be drawn to the golden glow coming from inside the hedge.')
        time.sleep(2)
        print()
        print()
        sp('You use your hands to prise apart the hedge from the crack the light shines through and manage to pull it apart wide enough for you to climb in.')
        time.sleep(2)
        print()
        print()
        move_W()
    elif response == 'South':
        sp('Who does that voice belong to?')
        time.sleep(2)
        print()
        print()
        sp('How do they know your name?')
        time.sleep(2)
        print()
        print()
        sp('This curiosity drives you South in search of answers.')
        time.sleep(2)
        print()
        print()
        move_S()
    elif response == 'East':
        sp('You venture towards the narrow path again.')
        time.sleep(2)
        print()
        print()
        sp('You feel suffocated immediately but make it through in a hurry.')
        time.sleep(2)
        print()
        print()
        move_E()



def square_11():
    sp("Old, rusty filing cabinets line the West side of the hedge.The one furthest to the right seems to be rattling.")
    time.sleep(2)
    print()
    print()
    sp("As you cautiously approach, you hear something bouncing around on the inside of what appears to be the top drawer.")
    time.sleep(2)
    print()
    print()
    sp("Your hand trembles as you reach out to grab the handle.")
    time.sleep(2)
    print()
    print()
    sp("Just as your fingertips are inches away, the drawer crashes open like it was shot out of a cannon.")
    time.sleep(2)
    print()
    print()
    sp("It’s a miracle that it remained on its tracks and remained in the cabinet.")
    time.sleep(2)
    print()
    print()
    sp("As you peer over and into the open drawer...")
    time.sleep(2)
    print()
    print()
    sp("You see...")
    time.sleep(2)
    print()
    print()
    sp("Yourself...")
    time.sleep(2)
    print()
    print()
    sp("It's a mirror.")
    time.sleep(2)
    print()
    print()
    sp("It has a handle so you pick it up, your hands still trembling.")
    time.sleep(2)
    print()
    print()
    sp("As you raise it in front of your face, you see it.")
    time.sleep(2)
    print()
    print()
    sp("The blood.")
    time.sleep(2)
    print()
    print()
    sp("Drenched, head to toe.")
    time.sleep(2)
    print()
    print()
    sp("A hard shiver down your spine makes you drop the mirror. You hear the glass break on the ground below.")
    time.sleep(2)
    print()
    print()
    sp("Ahead, to your North, there looks to be an opening in the hedge with nothing but a dry pile of dead leaves occupying the pathway.")
    time.sleep(2)
    print()
    print()
    sp("East lies the path you came from.")
    time.sleep(2)
    print()
    print()
    response=input('Which way would you like to go? [North/East/(Open Map)]: ')
    time.sleep(2)
    print()
    print()
    while response != 'North' and response != 'East':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [North/East/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp("I know it's nice and calm here but you really need to keep moving...")
            time.sleep(2)
            print()
            print()
            sp("You don't want to be trapped here forever, do you?")
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [North/East/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
    if response == 'North':
            sp('You walk towards the opening, accidentally stepping on the broken glass from the mirror. You hear it crack under your feet.')
            time.sleep(2)
            print()
            print()
            sp("You look down to assess the damage. You're wearing boots, no need to worry.")
            time.sleep(2)
            print()
            print()
            sp("Pressing on towards the opening, you kick the first few leaves aside and step into the main pile.")
            time.sleep(2)
            print()
            print()
            move_N()
    elif response == 'East':
         sp("You turn around and walk towards the opening, accidentally stepping on the broken glass from the mirror. You hear it crack beneath your feet.")
         time.sleep(2)
         print()
         print()
         sp("You look down to assess the damage. You're wearing boots, no need to worry.")
         time.sleep(2)
         print()
         print()
         sp("Let's get out of here!")
         time.sleep(2)
         print()
         print()
         move_E()



def square_15():
    sp("You dust yourself off and look around.")
    time.sleep(2)
    print()
    print()
    sp("Nothing...")
    time.sleep(2)
    print()
    print()
    sp("It's all rather quiet here.")
    time.sleep(2)
    print()
    print()
    sp("You seem to be in an alcove within the hedges and there is a narrow pathway to your West..")
    time.sleep(2)
    print()
    print()
    sp("Back North is the spider webs.")
    time.sleep(2)
    print()
    print()
    response=input('Which way would you like to go? [North/West/(Open Map)]: ')
    time.sleep(2)
    print()
    print()
    while response != 'North' and response!='West':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            response=input('Which way would you like to go? [North/West/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp("I know it's nice and calm here but you really need to keep moving..")
            time.sleep(2)
            print()
            print()
            sp("You don't want to be trapped here forever, do you?")
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [North/West/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
    if response == 'North':
            sp('Ugh! Spider time again!')
            time.sleep(2)
            print()
            print()
            sp('You reach your hand into the web mass and instantly feel them crawling.')
            time.sleep(2)
            print()
            print()
            sp("I guess you're getting used to this now.")
            time.sleep(2)
            print()
            print()
            sp('You submerge yourself in the webbing.')
            print('\n')
            move_N()
    elif response == 'West':
         sp("You carefully follow the narrow pathway, the walls feel like they're inching closer to you with every step you take.")
         time.sleep(2)
         print()
         print()
         sp("It's closing in.")
         time.sleep(2)
         print()
         print()
         sp('You pick up the pace and make it down the pathway before being enclosed in the hedges.')
         print()
         print()
         move_W()



def square_6():
    sp('The pile of leaves crumble underneath the weight of your body.')
    time.sleep(2)
    print()
    print()
    sp('You plummet instantly.')
    time.sleep(2)
    print()
    print()
    sp('Suddenly you feel weightless. The darkness is terrifying but you sense a calm in the atmosphere.')
    time.sleep(2)
    print()
    print()
    sp('A flash of light.')
    time.sleep(2)
    print()
    print()
    move_S()
    move_E()
    move_N()
    move_N()
    move_E()



def square_18():
    sp("You only slightly push the door but it swings wide open...")
    time.sleep(2)
    print()
    print("                                             ,--,  ,.-.")
    print("             ,                   \,       '-,-`,'-.' | ._")
    print("            /|           \    ,   |\         }  )/  / `-,',")
    print("           [ '          |\  /|   | |        /  \|  |/`  ,`")
    print("           | |       ,.`  `,` `, | |  _,...(   (      _',")
    print("           \  \  __ ,-` `  ,  , `/ |,'      Y     (   \_L\ ")
    print("            \  \_\,``,   ` , ,  /  |         )         _,/")
    print("             \  '  `  ,_ _`_,-,<._.<        /         /")
    print("              ', `>.,`  `  `   ,., |_      |         /")
    print("                \/`  `,   `   ,`  | /__,.-`    _,   `\ ")
    print("            -,-..\  _  \  `  /  ,  / `._) _,-\`       \ ")
    print("             \_,,.) /\    ` /  / ) (-,, ``    ,        | ")
    print("            ,` )  | \_\       '-`  |  `(               \ ")
    print("           /  /```(   , --, ,' \   |`<`    ,            |")
    print("          /  /_,--`\   <\  V /> ,` )<_/)  | \      _____)")
    print("    ,-, ,`   `   (_,\ \    |   /) / __/  /   `----`")
    print("   (-, \           ) \ ('_.-._)/ /,`    /")
    print("   | /  `          `/ \\ V   V, /`     /")
    print(",--\(        ,     <_/`\\     ||      /")
    print("(   ,``-     \/|         \-A.A-`|     /")
    print(",>,_ )_,..(    )\          -,,_-`  _--`")
    print("(_ \|`   _,/_  /  \_            ,--`")
    print("\( `   <.,../`     `-.._   _,-`")
    print("  `                      ```")
    print()
    print()
    print()
    sp("A horned beast appears, practically steaming from the nose.")
    time.sleep(2)
    print()
    print()
    sp("Its sudden arrival stuns you and sends you stumbling backwards through the door and it swings shut.")
    time.sleep(2)
    print()
    print()
    move_W()



def square_17():
    sp("The tree in the distant South is now more visible but you still can't make anything else out in that direction.")
    time.sleep(2)
    print()
    print()
    sp("To your East, you see a wooden door.")
    time.sleep(2)
    print()
    print()
    sp("There is a message smeared on the door in blood.")
    time.sleep(2)
    print()
    print()
    sp("It's not very well lit here so it's hard to make out but on first glance it seems to read: BEWARE!")
    time.sleep(2)
    print()
    print()
    sp("You lean in to take a closer look and as you do, the blood scripture seems to begin to shift.")
    time.sleep(2)
    print()
    print()
    sp("It did say: BEWARE!")
    time.sleep(2)
    print()
    print()
    sp("But now it's morphing...")
    time.sleep(2)
    print()
    print()
    sp("The blood has settled again and a new message can be read.")
    time.sleep(2)
    print()
    print()
    sp("TOKONI!")
    time.sleep(2)
    print()
    print()
    sp("What could that mean?")
    time.sleep(2)
    print()
    print()
    sp("Back North seems rather tranquil.")
    time.sleep(2)
    print()
    print()
    response=input('Which way would you like to go? [North/East/South/(Open Map)]: ')
    time.sleep(2)
    print()
    print()
    while response != 'North' and response != 'East' and response != 'South':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            response=input('Which way would you like to go? [North/East/South/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp("Aren't you getting hungry? You may starve to death if you don't move quickly.")
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [North/East/South/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
    if response == 'North':
            sp('You step away from the bloodied door and head back towards tranquility.')
            time.sleep(2)
            print()
            print()
            move_N()
    elif response == 'East':
         sp("You edge slowly towards the bloodied door and reach out your hand...")
         time.sleep(2)
         print()
         print()
         move_E()
    elif response == 'South':
        sp("You wander towards the tree off in the distance.")
        time.sleep(2)
        print()
        print()
        sp("As you approach, a deafening squawk nearly pierces your ear drums.")
        time.sleep(2)
        print()
        print()
        sp("This momentarily stuns you but you press on nonetheless.")
        time.sleep(2)
        print()
        print()
        move_S()



def square_12():
    sp('Everything seems so calm here.')
    time.sleep(2)
    print('\n')
    sp('Peaceful, almost.')
    time.sleep(2)
    print('\n')
    print('SQUAWK!!!')
    time.sleep(2)
    print('\n')
    sp('Your eyes dart South.')
    time.sleep(2)
    print('\n')
    sp('You still don\'t see the source but you can tell it\'s close.')
    time.sleep(2)
    print('\n')
    sp('There\'s also an opening to your West.')
    time.sleep(2)
    print('\n')
    print('SQUAWK!!!')
    time.sleep(2)
    print('\n')
    sp('As you divert your attention South again, your peripheral vision catches the opening to the West turn from a luscious green hedge arch')
    time.sleep(2)
    print('\n')
    sp('into a hellish nightmare.')
    time.sleep(2)
    print('\n')
    sp('A waterfall of blood violently pours down from above and completely covers the opening.')
    time.sleep(2)
    print('\n')
    sp('North is back to the well lit area.')
    time.sleep(2)
    print('\n')

    response=input('Which way would you like to go? [West/South/North/(Open Map)]: ')
    time.sleep(2)
    print()
    print()

    while response != 'West' and response!='South' and response!='North':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print('\n')
            response=input('Which way would you like to go? [West/South/North/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('I know this is scary but you really can\'t just stand here. Let\'s keep it going!')
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [West/South/North/(Open Map)]: ')
            time.sleep(2)
            print()
            print()

    if response == 'South':
        sp('You continue South to investigate the noises you hear.')
        time.sleep(2)
        print()
        print()
        sp('As you walk further in that direction, you can make out a tree ahead in the distance.')
        time.sleep(2)
        print()
        print()
        move_S()
    elif response == 'West':
        sp('Through the thick wall of blood, pouring down from above, you can still make out the passageway beyond it.')
        time.sleep(2)
        print()
        print()
        sp('You look at your hands, you\'re already covered in the stuff.')
        time.sleep(2)
        print('\n')
        sp('What\'s a little more?')
        time.sleep(2)
        print('\n')
        sp('You start slowly, creeping into the waterfall.')
        time.sleep(2)
        print('\n')
        sp('You feel the blood trickle from the crown of your head and down the back of your neck.')
        time.sleep(2)
        print('\n')
        sp('It\'s warm.')
        time.sleep(2)
        print('\n')
        sp('This feeling has you freaked out so you decide to burst through the rest of the way.')
        time.sleep(2)
        print('\n')
        move_W()
    elif response == 'North':
        sp('This is all too creepy for you.')
        time.sleep(2)
        print('\n')
        sp('You head back into the well lit area.')
        time.sleep(2)
        print('\n')
        sp('At least you can see properly again!')
        time.sleep(2)
        print('\n')
        move_N()



def square_10():
    sp('Now engulfed in this dense mass of web, the panic sets in.')
    time.sleep(2)
    print('\n')
    sp('Your movement has been severely limited.')
    time.sleep(2)
    print('\n')
    sp('As you try to wriggle free, you feel a crunch under your boot.')
    time.sleep(2)
    print('\n')
    sp('Suddenly, you feel them crawling all over your skin.')
    time.sleep(2)
    print('\n')
    print('Spiders.')
    time.sleep(2)
    print('\n')
    sp('They\'re only small but there must be hundreds of the little bastards.')
    time.sleep(2)
    print('\n')
    sp('Spiny, black legs and bodies but with glowing red eyes.')
    time.sleep(2)
    print('\n')
    sp('You reach your arms out to either side of you and feel the hedge walls.')
    time.sleep(2)
    print('\n')
    sp('You hear your name called again from the South.')
    time.sleep(2)
    print('\n')
    print(f'{name}...')
    time.sleep(2)
    print('\n')
    sp('To your North is the telephone you have previously tried to answer.')
    time.sleep(2)
    print('\n')

    response=input('Which way would you like to go? [South/North/(Open Map)]: ')
    time.sleep(2)
    print()
    print()

    while response != 'South' and response != 'North':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print('\n')
            response=input('Which way would you like to go? [South/North/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('Either you suffocate in this web or the spiders turn you into a chrysalid. I\'d keep it moving if I were you.')
            time.sleep(2)
            print('\n')
            response=input('Which way would you like to go? [South/North/(Open Map)]: ')
            time.sleep(2)
            print()
            print()

    if response == 'South':
        sp('You rip and tear at the web to make your way through.')
        time.sleep(2)
        print('\n')
        sp('You follow the mystery voice as a guide.')
        time.sleep(2)
        print('\n')
        sp('You eventually rip through the webbing. The force of which you do so sends you falling flat on your face.')
        time.sleep(2)
        print('\n')
        sp('The spiders have stayed behind in the web but you have several bite marks.')
        time.sleep(2)
        print('\n')
        move_S()
    elif response == 'North':
        sp('You eventually rip through the webbing. The force of which you do so sends you falling flat on your face.')
        time.sleep(2)
        print('\n')
        sp('The spiders have stayed behind in the web but you have several bite marks.')
        time.sleep(2)
        print('\n')
        move_N()



def square_7():
    sp('The loud squawking from the South catches your attention again, but you cannot see the source.')
    time.sleep(2)
    print('\n')
    sp('You\'re in a well lit area. Many torches illuminate your surroundings, but there isn\'t much to see.')
    time.sleep(2)
    print('\n')
    sp('Just lights and hedges surround you.')
    time.sleep(2)
    print('\n')
    sp('You hear the squawk again to the South, it sounds more frantic this time.')
    time.sleep(2)
    print('\n')
    sp('To your North is a small opening you have previously visited.')
    time.sleep(2)
    print('\n')
    response=input('Which way would you like to go? [North/South/(Open Map)]: ')
    time.sleep(2)
    print()
    print()
    while response != 'North' and response!='South':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [North/South/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('If you ever want to get out of here, I suggest you keep moving.')
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [North/South/(Open Map)]: ')
            time.sleep(2)
            print()
            print()

    if response == 'South':
        sp('Your intrigue surrounding the noises you hear compels you South.')
        time.sleep(2)
        print('\n')
        sp('A clearing is ahead. It looks clear and safe.')
        time.sleep(2)
        print('\n')
        sp('You walk in that direction.')
        time.sleep(2)
        print('\n')
        move_S()
    elif response == 'North':
        sp('You turn back and head North, in the direction of the fog wall you previously passed through.')
        time.sleep(2)
        print('\n')
        move_N()



def square_5():
    sp('You\'re standing in a small opening.')
    time.sleep(2)
    print('\n')
    sp('In the corner by the hedges is a small table and atop it sits an old rotary telephone.')
    time.sleep(2)
    print('\n')
    sp('It rings.')
    time.sleep(2)
    print('\n')
    sp('Ring ring... Ring ring...')
    time.sleep(2)
    print('\n')
    sp('You pick it up to see who\'s calling but all you hear is "beeeeeeeeeeeeeeeeeeep."')
    time.sleep(2)
    print('\n')
    sp('There\'s nobody there. Just a dial tone.')
    time.sleep(2)
    print('\n')
    sp('The path Southwards is blocked by a huge web.')
    time.sleep(2)
    print('\n')
    sp('It\'s a good thing you\'re not scared of spiders, right?')
    time.sleep(2)
    print('\n')
    sp('West would lead you back into the frost.')
    time.sleep(2)
    print('\n')

    response=input('Which way would you like to go? [South/West/(Open Map)]: ')
    time.sleep(2)
    print()
    print()

    while response != 'South' and response!='West':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print('\n')
            response=input('Which way would you like to go? [South/West/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('Look, I know spiders aren\'t the nicest of things and nobody wants to freeze but we can\'t just stand here all day. You need to decide which way you want to go.')
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [South/East/(Open Map)]: ')
            time.sleep(2)
            print()
            print()

    if response == 'South':
        sp('You reach into the web.')
        time.sleep(2)
        print('\n')
        sp('Wow, this is dense.')
        time.sleep(2)
        print('\n')
        sp('What on earth spun this?')
        time.sleep(2)
        print('\n')
        sp('Braving the unknown, you step into the web.')
        time.sleep(2)
        print('\n')
        move_S()
    elif response == 'West':
        sp('You turn back towards the frost, bracing yourself to be hit with the force of a thousand arctic winters as you enter the icy hell.')
        time.sleep(2)
        print('\n')
        move_W()



def square_4():
    sp('A bitter frost encompasses the area around you.')
    time.sleep(2)
    print('\n')
    sp('You see nothing but ice.')
    time.sleep(2)
    print('\n')
    sp('Your heart rate slows, almost to a stop.')
    time.sleep(2)
    print('\n')
    sp('Icicles are starting to form from your fingers.')
    time.sleep(2)
    print('\n')
    sp('You must quickly leave this area to survive.')
    time.sleep(2)
    print('\n')

    response=input('Which way would you like to go? [East/West/(Open Map)]: ')
    time.sleep(2)
    print()
    print()

    while response != 'East' and response != 'West':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print('\n')
            response=input('Which way would you like to go? [East/West/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('You don\'t really want to freeze to death, do you?')
            time.sleep(2)
            print('\n')
            sp('Best get moving, quick!')
            time.sleep(2)
            print('\n')
            response=input('Which way would you like to go? [East/West/(Open Map)]: ')
            time.sleep(2)
            print()
            print()

    if response == 'East':
        sp('You move as fast as your half frozen body will allow you to drag it.')
        time.sleep(2)
        print('\n')
        sp('Finally you escape the frost and can see the hedges again.')
        time.sleep(2)
        print('\n')
        move_E()
    elif response == 'West':
        sp('You drag your half frozen body back through the vines.')
        time.sleep(2)
        print('\n')
        sp('It feels as if the thorns could shatter you if caught up in them but you make it through relatively unscathed.')
        time.sleep(2)
        print('\n')
        move_W()



def square_2():
    sp('A fog door? That was unusual.')
    time.sleep(2)
    print()
    print()
    sp('Although, nothing is usual about this place.')
    time.sleep(2)
    print()
    print()
    sp('There isn\'t much around you. Just some hedges.')
    time.sleep(2)
    print()
    print()
    sp('It\'s still deathly quiet.')
    time.sleep(2)
    print()
    print()
    sp('Until...')
    time.sleep(2)
    print()
    print()
    sp('A distant but loud squawk to the South diverts your attention to that direction.')
    time.sleep(2)
    print()
    print()
    sp('The corridor is long and you\'re unable to see more than a few meters ahead.')
    time.sleep(2)
    print()
    print()
    sp('The fog door you passed through earlier is to your East.')
    time.sleep(2)
    print()
    print()
    response=input('Which way would you like to go? [South/East/(Open Map)]: ')
    time.sleep(2)
    print()
    print()
    print()
    while response != 'South' and response != 'East':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [South/East/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('Something calling your name or a high pitched squawk? Not the best of choices but we must press on, regardless.')
            time.sleep(2)
            print()
            print()
            sp('Unless you want to die here?')
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [South/East/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
    if response == 'South':
        sp('You press forward regardless, towards the source of the shrieking squawk you heard.')
        time.sleep(2)
        print()
        print()
        move_S()
    elif response == 'East':
        sp('You turn back towards the fog door, once again stretching your arms out in front of you as you traverse it.')
        time.sleep(2)
        print()
        print()
        move_E()



def square_3():
    sp("The mystery voice is once again beckoning you, it appears to be coming from Eastwards.")
    time.sleep(2)
    print()
    print()
    sp("You look in that direction to see a thin wall of vines with thorns dripping yet more blood.")
    time.sleep(2)
    print()
    print()
    sp("You should be able to pass these relatively easily.")
    time.sleep(2)
    print()
    print()
    sp("To your West...")
    time.sleep(2)
    print()
    print()
    sp("silence")
    time.sleep(2)
    print()
    print()
    sp("...an eerie silence.")
    time.sleep(2)
    print()
    print()
    sp("There is a light fog to the West but the path seems clear.")
    time.sleep(2)
    print()
    print()
    response=input('Which way would you like to go? [East/West/(Open Map)]: ')
    time.sleep(2)
    print()
    while response != 'East' and response != 'West':
        if response=='Open Map':
            open_map()
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [East/West/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
        else:
            sp('Unless you want to be stuck here forever, I\'d choose East or West.')
            time.sleep(2)
            print()
            print()
            response=input('Which way would you like to go? [East/West/(Open Map)]: ')
            time.sleep(2)
            print()
            print()
    print()
    print()
    if response == 'East':
        sp("You grip the middle few vines and part them to create a gap to climb through.")
        time.sleep(2)
        print()
        print()
        sp("Several of the thorns pierce your skin.")
        time.sleep(2)
        print()
        print()
        sp('You feel the pain but cannot tell whether the blood you see is yours or not.')
        time.sleep(2)
        print()
        print()
        sp('You climb through the opening.')
        print()
        print()
        move_E()
    elif response == 'West':
        sp('You reach your arms out in front of you ensuring you don\'t walk into anything whilst traversing the fog.')
        time.sleep(2)
        print()
        print()
        sp('The fog suddenly dissipates and you can see around you again.')
        print()
        print()
        move_W()



def game_start():
    print()
    print()
    sp("A T3AM Gaming Production")
    time.sleep(2)
    print()
    print()
    sp("HORROR/MYSTERY")
    time.sleep(2)
    print()
    print()
    sp("Age: 18+")
    time.sleep(2)
    print()
    print()
    print()
    sp("Welcome to")
    time.sleep(2)
    print()
    print()
    sp("...")
    time.sleep(2)
    print()
    print()
    print("\033[1;32m ________________________________________________")  
    print("\033[1;32m Y   _   YY   Y   YY   _   YY   _   Y(   _   Y! ! ⓒ")
    print("\033[1;32m |   l   ||       ||   l   |l___|   ||  l____|! !")
    print("\033[1;32m |   _   ||  \_/  ||   _   | /  ___/ |  ____) !_!")
    print("\033[1;32m |   |   ||   |   ||   |   ||   l   Y|  l    | _ ")
    print("\033[1;32m l___|___||___l___|l___|___|l_______|l_______|!_!")
    time.sleep(2)
    print()
    print()
    print()
    global name
    global Age
    global difficulty
    sp("\033[0mWhat is your name, challenger?")
    time.sleep(2)
    print("\n")
    name = input()
    time.sleep(2)
    print("\n")
    sp(f"And what is your age, {name}??")
    time.sleep(2)
    print()
    print()
    Age = input()
    if Age >= "17.99":
        print()
        print()
        sp(f"Congratulations, {name} you're old enough to play.")
        time.sleep(2)
        print()
        print()
        print()
    else:
        print()
        print()
        sp(f"Sorry you're too young to play this game, {name}. You need to be 18 and above.")
        time.sleep(2)
        print()
        print()
        print()
        sp("Restart game maybe?")
        time.sleep(2)
        print()
        print()
        print()
        exit()
    sp("Choose your difficulty.")
    time.sleep(2)
    print()
    print()
    difficulty = input("Easy, Medium or Hard: ")
    time.sleep(2)
    print()
    print()
    if difficulty == "Easy" or difficulty == "easy" or difficulty == "EASY":
        sp(f"WIMP... Oh, sorry. Come forth, {name}...")
        time.sleep(2)
        print()
        print()
    elif difficulty == "Medium" or difficulty == "medium" or difficulty == "MEDIUM":
        sp(f"Is that you {name}? Well, don't get lost...")
        time.sleep(2)
        print()
        print()
    elif difficulty == "Hard" or difficulty == "hard" or difficulty == "HARD" or difficulty == "Hard " or difficulty == "hard " or difficulty == "HARD " or difficulty == " Hard" or difficulty == " hard" or difficulty == " HARD":
        sp(f"Finally, a worthy opponent! Let's see how you get on, {name}!")
        time.sleep(2)
        print()
        print()
    else:
        sp("Sorry invalid input.")
        time.sleep(2)
        print()
        print()



def game_intro():
    print()
    print()
    sp(f"Welcome to the Maze {name}, escape")
    time.sleep(2)
    print()
    print()
    sp(f"...if you dare.")
    time.sleep(2)
    print()
    print()
    print()
    sp("You reach across and clink your glass, celebrating your success.")
    time.sleep(2)
    print()
    print()
    sp("Your partner throws a smile your way and...")
    time.sleep(2)
    print()
    print()
    print()
    print("\033[1m BANG! \033[0m")
    time.sleep(2)
    print()
    print()
    sp("Your eyes open.")
    time.sleep(2)
    print()
    print()
    sp("It was a dream.")
    time.sleep(2)
    print()
    print()
    sp("Your spine shudders.")
    time.sleep(2)
    print()
    print()
    sp("You can barely see a meter ahead of you and the ground you’re sitting on is soft but wet.")
    time.sleep(2)
    print()
    print()
    sp("You run your fingers beside you and conclude that it’s grass, but why is it so wet?")
    time.sleep(2)
    print()
    print()
    sp("Two bursts of light appear ahead.")
    time.sleep(2)
    print()
    print()
    sp("Flames from wicker torches above illuminate the surrounding area.")
    time.sleep(2)
    print()
    print()
    sp("You see an entrance within what appears to be a hedge row.")
    time.sleep(2)
    print()
    print()
    sp("A voice emanates from beyond the entrance.")
    time.sleep(2)
    print()
    print()
    sp("It’s faint, but you think you hear your name.")
    time.sleep(2)
    print()
    print()
    sp(f"{name}...")
    time.sleep(3)
    print()
    print()
    sp(f"{name}...")
    time.sleep(3)
    print()
    print()
    sp(f"{name}...")
    time.sleep(3)
    print()
    print()
    sp("You’re scared, but you feel compelled to follow the voice.")
    time.sleep(2)
    print()
    print()
    sp("As you rise to your feet, you feel your clothing clinging to the ground below.")
    time.sleep(2)
    print()
    print()
    sp("On inspection, you know now why the grass was wet.")
    time.sleep(2)
    print()
    print()
    sp("You’re covered in blood.")
    time.sleep(2)
    print()
    print()
    sp("It has dried on the spot you woke from, but everything else around you seems to be soaked.")
    time.sleep(2)
    print()
    print()
    sp("You're surrounded by darkness for as far as your eyes can see.")
    time.sleep(2)
    print()
    print()
    sp("You once again hear that faint voice...")
    time.sleep(2)
    print()
    print()
    sp(f"{name}...")
    time.sleep(2.5)
    print()
    print()
    sp("You walk forwards reservedly, beyond the torches and into the opening in the hedge.")
    time.sleep(2)
    print()
    print()
    sp("As you enter the opening, torches light around you.")
    time.sleep(2)
    print()
    print()
    sp("You see it now.")
    time.sleep(2)
    print()
    print()
    sp("It’s Amaze!...")
    time.sleep(2)
    print()
    print()
    print()
    print()
    sp("\033[1mHow to play the game\033[0m")
    time.sleep(2)
    print()
    sp('As you navigate the maze you will be given the choice to type either: \n "North", \n "South", \n "East", \n "West", or \n "Open Map" (to open a map of the Maze.)')
    time.sleep(2)
    print()
    sp('Note: these options are case-senstive.')
    time.sleep(2)
    print()
    print()
    sp("\033[1mWhat the Map means\033[0m")
    time.sleep(2)
    print()
    sp(' "X" marks where you currently are in the maze, \n "O" shows where you\'ve been.')
    time.sleep(2)
    print()
    print()
    print()
    print()




def the_squares():
    if current_position == [0,1]:
        square_2()
    elif current_position == [0,2]:
        square_3()
    elif current_position == [0,3]:
        square_4()
    elif current_position == [0,4]:
        square_5()
    elif current_position == [1,0]:
        square_6()
    elif current_position == [1,1]:
        square_7()
    elif current_position == [1,4]:
        square_10()
    elif current_position == [2,0]:
        square_11()
    elif current_position == [2,1]:
        square_12()
    elif current_position == [2,2]:
        square_13()
    elif current_position == [2,3]:
        square_14()
    elif current_position == [2,4]:
        square_15()
    elif current_position == [3,1]:
        square_17()
    elif current_position == [3,2]:
        square_18()
    elif current_position == [3,3]:
        square_19()
    elif current_position == [4,1]:
        square_22()
    elif current_position == [4,3]:
        square_24()
    elif current_position == [4,4]:
        square_25()







game_start()
game_intro()
while current_position != [4,2]:
    update_visited_positions()
    update_maze()
    the_squares()
square_23()
exit()
